# Generated by Django 5.2 on 2025-04-11 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('supertype', models.CharField(max_length=256, null=True)),
                ('subtype_l', models.TextField(default='')),
                ('hp', models.IntegerField(default=-1)),
                ('type_l', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('rules', models.TextField(default='')),
                ('weakness_h', models.TextField(default='')),
                ('resistance_h', models.TextField(default='')),
                ('retreat_l', models.TextField(default='')),
                ('number', models.CharField(default='', max_length=64)),
                ('artist', models.CharField(default='', max_length=256)),
                ('national_l', models.TextField(default='')),
                ('flavorText', models.TextField(default='')),
                ('image', models.ImageField(upload_to='pokemon_images/')),
                ('average_sell_price', models.FloatField(default=0)),
                ('low_price', models.FloatField(default=0)),
                ('trend_price', models.FloatField(default=0)),
                ('suggested_price', models.FloatField(default=0)),
                ('sell_price', models.FloatField(default=0)),
                ('evolvesFrom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cost_s', models.TextField()),
                ('text', models.TextField()),
                ('damage', models.CharField(max_length=64)),
                ('pokemons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.pokemon')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='ix_attack_name')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='uniq_attack_name')],
            },
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('type', models.CharField(max_length=256)),
                ('pokemons', models.ManyToManyField(to='trading.pokemon')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='ix_ability_name')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='uniq_ability_name')],
            },
        ),
    ]
