# Generated by Django 5.2 on 2025-04-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_pokemon_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='cost_price',
            field=models.FloatField(default=0),
        ),
    ]
