# Generated by Django 5.2 on 2025-04-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_pokemon_cost_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='evolvesFrom',
            new_name='evolves_from',
        ),
    ]
