# Generated by Django 5.2 on 2025-04-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_rename_evolvesfrom_pokemon_evolves_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='description',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='tcg_id',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
