# Generated by Django 5.2 on 2025-04-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_remove_pokemon_description_pokemon_tcg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='tcg_id',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, unique=True),
        ),
    ]
