# Generated by Django 5.2 on 2025-04-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_alter_pokemon_evolves_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='card',
            field=models.ImageField(blank=True, null=True, upload_to='pokemon_card/'),
        ),
    ]
