# Generated by Django 5.2 on 2025-04-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_pokemon_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='artist',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='flavorText',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='national_l',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='resistance_h',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='retreat_l',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='rules',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='supertype',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weakness_h',
            field=models.TextField(blank=True, default=''),
        ),
    ]
