# Generated by Django 5.2 on 2025-04-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_daily_reward',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
